### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by NICECPU** [loujc/BNN-VAD-pytorch#1]
你好，请问我运行你的实例程序出现了这个问题是为啥啊？
(VAD) E:\Python_Project\VAD\BNN-VAD-pytorch>python main_binary.py --model resnet_binary --save resnet18_binary --dataset cifar10
D:\softwore\conda\envs\VAD\lib\site-packages\torch\package\_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally
at  ..\torch\csrc\utils\tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
Traceback (most recent call last):
  File "main_binary.py", line 11, in <module>
    import models
  File "E:\Python_Project\VAD\BNN-VAD-pytorch\models\__init__.py", line 1, in <module>
    from input.processor import *
ModuleNotFoundError: No module named 'input'

**Comment by loujc** [comment]
你要运行什么功能呢

**Comment by NICECPU** [comment]
我已经解决了，谢谢你的关注！

> 你要运行什么功能呢

**Comment by loujc** [comment]
好的
